/*
 * This file is generated by jOOQ.
 */
package com.github.dnsq.jooq;


import com.github.dnsq.jooq.tables.Click;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>click</code>.
     */
    public static final Click CLICK = Click.CLICK;
}
