/*
 * This file is generated by jOOQ.
 */
package com.github.dnsq.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Click implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer count;

    public Click() {}

    public Click(Click value) {
        this.id = value.id;
        this.count = value.count;
    }

    public Click(
        Integer id,
        Integer count
    ) {
        this.id = id;
        this.count = count;
    }

    /**
     * Getter for <code>click.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>click.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>click.count</code>.
     */
    public Integer getCount() {
        return this.count;
    }

    /**
     * Setter for <code>click.count</code>.
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Click other = (Click) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.count == null) {
            if (other.count != null)
                return false;
        }
        else if (!this.count.equals(other.count))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.count == null) ? 0 : this.count.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Click (");

        sb.append(id);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
