# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build native image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-amd64:
    name: Build native image(amd64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: GitHub Action for GraalVM
      #   uses: graalvm/setup-graalvm@v1
      #   with:
      #     java-version: '21'
      #     distribution: 'graalvm' # See 'Options' for all available distributions
      #     cache: 'maven'
      - name: Set VERSION environment variable
        run: |
          echo "VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zhoukq
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./src/main/docker/Dockerfile.multistage
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            zhoukq/dnsq:${{ env.VERSION }}-amd64

  build-arm64:
    name: Build native image(arm64)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      # - name: GitHub Action for GraalVM
      #   uses: graalvm/setup-graalvm@v1
      #   with:
      #     java-version: '21'
      #     distribution: 'graalvm' # See 'Options' for all available distributions
      #     cache: 'maven'
      - name: Set VERSION environment variable
        run: |
          echo "VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      #      - name: Set up QEMU
      #        uses: docker/setup-qemu-action@v3
      #
      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zhoukq
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./src/main/docker/Dockerfile.multistage
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            zhoukq/dnsq:${{ env.VERSION }}-arm64

  create-manifest:
    needs: [build-amd64, build-arm64]  # 等待前两个完成
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zhoukq
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push Manifest
        run: |
          docker manifest create zhoukq/dnsq:${{ env.VERSION }} \
            --amend zhoukq/dnsq:${{ env.VERSION }}-amd64 \
            --amend zhoukq/dnsq:${{ env.VERSION }}-arm64
          
          docker manifest push zhoukq/dnsq:${{ env.VERSION }}

