# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build native image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GitHub Action for GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm' # See 'Options' for all available distributions
          cache: 'maven'
      - name: Set VERSION environment variable
        run: |
          echo "VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build with Maven
        run: |
          uname -a
          ./mvnw install -Dnative -DskipTests=true \
          -Dquarkus.native.container-build=true \
          -Dquarkus.native.container-runtime=docker \
          -Dquarkus.container-image.build=true \
          -Dquarkus.native.march=compatibility \
          -Dquarkus.docker.buildx.platform=linux/amd64,linux/arm64 \
          -Dquarkus.docker.dockerfile-native-path=src/main/docker/Dockerfile.native-micro \
          -Dquarkus.container-image.group=zhoukq \
          -Dquarkus.container-image.name=dnsq \
          -Dquarkus.container-image.tag=${{ env.VERSION }}-${{ github.run_number }} \
          -Dquarkus.container-image.additional-tags=${{ env.VERSION }}-${{ github.run_number }} \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.username=zhoukq \
          -Dquarkus.container-image.password=${{ secrets.DOCKERHUB_TOKEN }}
  
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
